# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCODvHhhjRaDp45E6SsDIObxzXbwDS8N
"""

import math
import pandas as pd
import streamlit as st
import io
from io import BytesIO


CUENTAS_OBJETIVO = [
    "Ingresos de actividades ordinarias",
    "Deudores comerciales y otras cuentas por cobrar corrientes",
]
UMBRAL_USD = 40_000_000

st.set_page_config(page_title="Informe IFRS - Empresas Grandes", layout="centered")
st.title("📊 Análisis de Empresas IFRS")
st.markdown("""
1. Descarga el último informe desde:
   👉 [CMF - Estadísticas IFRS](https://www.cmfchile.cl/institucional/estadisticas/estadisticas_ifrs.php)

2. Luego, sube el archivo TXT que descargaste.

3. Ingresa el valor del dólar usado en el informe.

4. El sistema filtrará las empresas con ingresos o cuentas por cobrar sobre 40 millones USD.
""")

# Subir archivo
archivo = st.file_uploader("📂 Subir archivo .txt del informe IFRS", type=["txt"])

# Ingresar valor del dólar
valor_dolar = st.number_input("💵 Valor del dólar (CLP por USD)", min_value=100.0, max_value=2000.0, step=1.0)

if archivo and valor_dolar:
    contenido = archivo.read().decode("latin-1", errors="ignore")
    df = pd.read_csv(
        io.StringIO(contenido),
        sep=";",
        header=None,
        names=[
            "periodo", "codigo_entidad", "nombre_entidad", "tipo",
            "moneda", "cuenta", "monto", "taxonomia", "origen"
        ],
        dtype=str
    )
    df["monto"] = pd.to_numeric(df["monto"], errors="coerce")

    # Convertir CLP a USD
    def convertir(row):
        if pd.isna(row["monto"]):
            return math.nan
        if row["moneda"] == "CLP":
            return row["monto"] / valor_dolar
        elif row["moneda"] == "USD":
            return row["monto"]
        return math.nan

    df = df[df["cuenta"].isin(CUENTAS_OBJETIVO)].copy()
    df["monto_usd"] = df.apply(convertir, axis=1)

    # Tabla pivot
    tabla = df.pivot_table(
        index=["codigo_entidad", "nombre_entidad"],
        columns="cuenta",
        values="monto_usd",
        aggfunc="first"
    ).reset_index()

    tabla = tabla.rename(columns={
        "Ingresos de actividades ordinarias": "ingresos_usd",
        "Deudores comerciales y otras cuentas por cobrar corrientes": "deudores_usd"
    })

    tabla["max_usd"] = tabla[["ingresos_usd", "deudores_usd"]].max(axis=1)

    resultado = tabla[tabla["max_usd"] >= UMBRAL_USD].sort_values("max_usd", ascending=False)

    # Mostrar resultados
    st.success(f"✅ Se encontraron {len(resultado)} empresas sobre {UMBRAL_USD:,} USD.")
    st.dataframe(resultado)

    output = BytesIO()
    
    with pd.ExcelWriter(output, engine="xlsxwriter") as writer:
        resultado.to_excel(writer, index=False, sheet_name="Empresas")
    
    # IMPORTANTE: volver al inicio del buffer
    output.seek(0)
    
    st.download_button(
        label="💾 Descargar resultado en Excel",
        data=output,
        file_name="empresas_grandes_ifrs.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )
